//! The installer's output: `<root>/config/hearth.env`, rendered from the
//! install record.
//!
//! This is the seam the whole configuration story hangs on. The probe's plan
//! decided the values, the record froze them, this renders them, and every
//! backend process reads the rendered file and nothing else. No consumer
//! carries its own defaults; `hearth_probe::defaults` is the single home for
//! the product constants that appear here.
//!
//! The backend testbed keeps `backend/scripts/render_config.py` for runs
//! without a client; both follow config/hearth.env.example, and this one is
//! canonical for installed machines.

use hearth_probe::defaults as d;
use std::path::{Path, PathBuf};

fn slash(p: &Path) -> String {
    p.to_string_lossy().replace('\\', "/")
}

/// Render from `<root>/hearth-install.json`. Overwrites: a re-render after a
/// reinstall is the point, so hand edits live only until then, and the header
/// says so.
pub fn render(root: &Path) -> Result<PathBuf, String> {
    let record_path = root.join("hearth-install.json");
    let text = std::fs::read_to_string(&record_path)
        .map_err(|e| format!("no install record at {}: {}", record_path.display(), e))?;
    let record: serde_json::Value =
        serde_json::from_str(&text).map_err(|e| format!("unreadable record: {}", e))?;
    let plan = record.get("plan").ok_or("record has no plan")?;

    let weights_dir = record
        .get("weights_dir")
        .and_then(|v| v.as_str())
        .map(PathBuf::from)
        .unwrap_or_else(|| root.join(d::REL_MODELS));
    let n_ctx = plan.get("n_ctx").and_then(|v| v.as_u64()).unwrap_or(0);
    let model_file = plan.get("file").and_then(|v| v.as_str());
    let accel = plan.get("backend").and_then(|v| v.as_str()).unwrap_or("cpu");
    let cuda_arch = plan.get("cuda_arch").and_then(|v| v.as_str());
    let coexist = plan.get("coexist").and_then(|v| v.as_bool()).unwrap_or(false);
    let completed = record
        .get("completed_unix")
        .and_then(|v| v.as_u64())
        .unwrap_or(0);

    let mut out = String::new();
    let mut line = |s: String| {
        out.push_str(&s);
        out.push('\n');
    };

    line("# hearth.env, GENERATED by the installer from hearth-install.json.".into());
    line("# Regenerated on every install; edits survive until then. The schema".into());
    line("# is documented in the backend's config/hearth.env.example.".into());
    line(format!("# record completed_unix: {}", completed));
    line(String::new());
    line("# Where things are".into());
    line(format!("HEARTH_BACKEND_DIR={}", slash(&root.join(d::REL_BACKEND))));
    line(format!("HEARTH_PYTHON={}", slash(&root.join(d::rel_python()))));
    line(format!("HEARTH_VOICE_PYTHON={}", slash(&root.join(d::rel_voice_python()))));
    line(format!("HEARTH_SUPERVISOR_BIN={}", slash(&root.join(d::rel_supervisor()))));
    line(format!("HEARTH_LLAMA_SERVER_BIN={}", slash(&root.join(d::rel_llama_server()))));
    line(format!("HEARTH_HOME={}", slash(&root.join(d::REL_HOME))));
    line(format!("HEARTH_ENGRAM={}", slash(&root.join(d::REL_ENGRAM))));
    line(format!("HF_HOME={}", slash(&root.join(d::REL_HF_CACHE))));
    // Symlinks need Developer Mode on Windows; a per-install cache uses
    // plain files instead. Costs duplicate bytes for one model, buys an
    // install that works on any machine.
    line("HF_HUB_DISABLE_SYMLINKS=1".into());
    line(format!("HEARTH_MODELS={}", slash(&weights_dir)));
    // WHICH file, not just which directory. Without this the persona's own
    // deep_model.id decides, and a persona ships one id while the plan picks a
    // tier per machine: every install that was not the persona's tier asked
    // llama-server for a model the installer never downloaded, and died at
    // boot with the house already on screen. The plan chose; the plan says so.
    if let Some(file) = model_file {
        line(format!(
            "HEARTH_DEEP_MODEL_FILE={}",
            slash(&weights_dir.join(file))
        ));
    }
    line(format!("HEARTH_LOG_DIR={}", slash(&root.join(d::REL_LOGS))));
    line(String::new());
    line("# The plan's decisions".into());
    if n_ctx > 0 {
        line(format!("HEARTH_LLAMA_CTX={}", n_ctx));
        // The same number to the harness, which otherwise packs prompts
        // against its own 32768 default while llama-server is running the
        // plan's window. Two budgets for one context is a truncation waiting
        // for a long enough conversation.
        line(format!("HEARTH_CTX_MAX_TOKENS={}", n_ctx));
    }
    line(format!("HEARTH_ACCEL={}", accel));
    if let Some(arch) = cuda_arch {
        line(format!("HEARTH_CUDA_ARCH={}", arch));
    }
    // A mixture-of-experts pick on a card that cannot hold it fully resident
    // runs its experts from system RAM (llama's --n-cpu-moe): only the active
    // slice streams per token, so CPU-resident experts are a design where
    // spilled dense weights are an accident. The accident was measured
    // 2026-08-08: the 26B ground at 0.3 tok/s spilled on a 16 GB card, and
    // 26 GB is unsloth's own fully-resident floor for it. Written here so the
    // lever survives every reinstall; a hand-added env line does not.
    let vram_bytes = record
        .get("machine")
        .and_then(|m| m.get("gpu"))
        .and_then(|g| g.get("vram_bytes"))
        .and_then(|v| v.as_u64());
    if let (Some(file), Some(vram)) = (model_file, vram_bytes) {
        if file.contains("A4B") && vram < 26_000_000_000 {
            line("HEARTH_LLAMA_CPU_MOE=99".into());
        }
    }
    // Readiness must scale with what the disk has to deliver: the 300s
    // default was tuned when models were 7 GB, and a cold 12-14 GB read at
    // this machine class's ~47 MB/s spends four-plus minutes before llama
    // can say hello (measured 2026-08-08; the window expired around a load
    // that was still succeeding). Budget a conservative 25 MB/s plus startup
    // slack, floored at the old default.
    if let Some(file) = model_file {
        if let Ok(meta) = std::fs::metadata(weights_dir.join(file)) {
            let secs = 300u64.max(meta.len() / (25 * 1024 * 1024) + 120);
            line(format!("HEARTH_LLAMA_HEALTH_TIMEOUT_S={}", secs));
        }
    }
    line(format!("HEARTH_COEXIST={}", if coexist { 1 } else { 0 }));
    line(String::new());
    line("# Ports: Hearth's own block".into());
    line(format!("HEARTH_PORT={}", d::PORT_GATEWAY));
    // The gateway alone faces the LAN, so phones and headsets on the same
    // network can be clients (the Valinor arrangement). Everything behind
    // it (llama, supervisor, TTS) stays loopback: one front door.
    line("HEARTH_HOST=0.0.0.0".into());
    line(format!("HEARTH_LLAMA_PORT={}", d::PORT_LLAMA));
    line("HEARTH_LLAMA_HOST=127.0.0.1".into());
    line(format!("HEARTH_RUST_WS_PORT={}", d::PORT_SUPERVISOR_WS));
    line("HEARTH_RUST_WS_HOST=127.0.0.1".into());
    line(format!("HEARTH_RUST_ASSET_PORT={}", d::PORT_SUPERVISOR_ASSETS));
    line("HEARTH_RUST_ASSET_HOST=127.0.0.1".into());
    line(format!("HEARTH_TTS_PORT={}", d::PORT_TTS));
    line(format!("HEARTH_BRAIN_BASE_URL=http://127.0.0.1:{}/v1", d::PORT_LLAMA));
    line(format!("HEARTH_LLAMA_BASE_URL=http://127.0.0.1:{}/v1", d::PORT_LLAMA));
    line(format!("HEARTH_BRAIN_SWITCH_WS_URL=ws://127.0.0.1:{}", d::PORT_SUPERVISOR_WS));
    line(String::new());
    line("# Behaviour".into());
    line("HEARTH_BRAIN_BACKEND=router".into());
    line(format!("HEARTH_TTS_SERVICE_URL=ws://127.0.0.1:{}/tts", d::PORT_TTS));
    line("HEARTH_TTS_BACKEND=remote".into());
    // Which voice engine, and everything that follows from it. omnivoice.cpp
    // emits 24 kHz; the rate is configured to match rather than resampled in
    // the middle, because the client is told the rate and plays what it is
    // told. The torch engine resamples to 48 kHz itself.
    let dict = hearth_probe::Dictionary::embedded().map_err(|e| e.to_string())?;
    if dict.voice.uses_cpp(std::env::consts::OS) {
        line("HEARTH_TTS_SERVICE=omnivoice-cpp".into());
        line("HEARTH_TTS_SAMPLE_RATE=24000".into());
        line(format!(
            "HEARTH_TTS_ENGINE_URL=http://127.0.0.1:{}",
            d::PORT_TTS_ENGINE
        ));
        line(format!("HEARTH_TTS_ENGINE_PORT={}", d::PORT_TTS_ENGINE));
        line(format!(
            "HEARTH_TTS_ENGINE_BIN={}",
            slash(&root.join(d::rel_tts_server()))
        ));
        line(format!(
            "HEARTH_TTS_VOICE_MODELS={}",
            slash(&root.join(d::REL_VOICE_MODELS))
        ));
        line(format!(
            "HEARTH_OMNIVOICE_TTS={}",
            slash(&root.join(d::rel_omnivoice_tts()))
        ));
        line(format!("HEARTH_TTS_STEPS={}", dict.voice.steps));
    } else {
        line("HEARTH_TTS_SERVICE=omnivoice".into());
        line("HEARTH_TTS_SAMPLE_RATE=48000".into());
    }
    // expandable_segments, the WSL-era allocator fix, is unsupported by
    // torch's CUDA allocator on Windows (verified in the native smoke:
    // warning, no effect, and 2.1 GiB reserved without it). Linux builds
    // reintroduce it; writing it here would only warn on every boot.
    line("HEARTH_WHISPER_MODEL=base".into());
    line("HEARTH_TOOLS_ENABLED=1".into());
    line("HEARTH_LLAMA_REASONING=auto".into());
    line(format!("HEARTH_DEFAULT_PERSONA={}", d::FIRST_PERSONA));
    line("HEARTH_SESSION_IDLE_S=300".into());
    // from: the machine's locale at install time. A bare place name in a
    // weather query resolves toward the machine's own country; an explicit
    // region in the query always outranks this.
    if let Some(region) = sys_locale::get_locale()
        .and_then(|l| l.split(['-', '_']).nth(1).map(|r| r.to_uppercase()))
        .filter(|r| r.len() == 2)
    {
        line(format!("HEARTH_REGION_BIAS={}", region));
    }

    let config_path = root.join(d::REL_CONFIG);
    if let Some(parent) = config_path.parent() {
        std::fs::create_dir_all(parent).map_err(|e| e.to_string())?;
    }
    std::fs::write(&config_path, out).map_err(|e| e.to_string())?;
    Ok(config_path)
}

/// Re-render on demand, for a repaired or upgraded install.
#[tauri::command]
pub fn probe_render_config(root: String) -> Result<String, String> {
    render(Path::new(&root)).map(|p| p.to_string_lossy().to_string())
}

#[cfg(test)]
mod tests {
    use super::*;

    /// Dev utility, not a test of anything: renders a real install root's
    /// hearth.env through the real code path, so the development machine's
    /// config is generated rather than hand-written. Gated on an env var so
    /// a normal test run never touches disk outside the repo.
    /// Usage: HEARTH_DEV_RENDER_ROOT=D:\Hearth cargo test -p app render_dev_root -- --nocapture
    #[test]
    fn render_dev_root() {
        let Ok(root) = std::env::var("HEARTH_DEV_RENDER_ROOT") else {
            return;
        };
        match render(Path::new(&root)) {
            Ok(path) => println!("rendered {}", path.display()),
            Err(e) => panic!("render failed: {}", e),
        }
    }
}
