//! The installer's output: `<root>/config/hearth.env`, rendered from the
//! install record.
//!
//! This is the seam the whole configuration story hangs on. The probe's plan
//! decided the values, the record froze them, this renders them, and every
//! backend process reads the rendered file and nothing else. No consumer
//! carries its own defaults; `hearth_probe::defaults` is the single home for
//! the product constants that appear here.
//!
//! The backend testbed keeps `backend/scripts/render_config.py` for runs
//! without a client; both follow config/hearth.env.example, and this one is
//! canonical for installed machines.

use hearth_probe::defaults as d;
use std::path::{Path, PathBuf};

fn slash(p: &Path) -> String {
    p.to_string_lossy().replace('\\', "/")
}

/// Render from `<root>/hearth-install.json`. Overwrites: a re-render after a
/// reinstall is the point, so hand edits live only until then, and the header
/// says so.
pub fn render(root: &Path) -> Result<PathBuf, String> {
    let record_path = root.join("hearth-install.json");
    let text = std::fs::read_to_string(&record_path)
        .map_err(|e| format!("no install record at {}: {}", record_path.display(), e))?;
    let record: serde_json::Value =
        serde_json::from_str(&text).map_err(|e| format!("unreadable record: {}", e))?;
    let plan = record.get("plan").ok_or("record has no plan")?;

    let weights_dir = record
        .get("weights_dir")
        .and_then(|v| v.as_str())
        .map(PathBuf::from)
        .unwrap_or_else(|| root.join(d::REL_MODELS));
    let n_ctx = plan.get("n_ctx").and_then(|v| v.as_u64()).unwrap_or(0);
    let accel = plan.get("backend").and_then(|v| v.as_str()).unwrap_or("cpu");
    let cuda_arch = plan.get("cuda_arch").and_then(|v| v.as_str());
    let coexist = plan.get("coexist").and_then(|v| v.as_bool()).unwrap_or(false);
    let completed = record
        .get("completed_unix")
        .and_then(|v| v.as_u64())
        .unwrap_or(0);

    let mut out = String::new();
    let mut line = |s: String| {
        out.push_str(&s);
        out.push('\n');
    };

    line("# hearth.env, GENERATED by the installer from hearth-install.json.".into());
    line("# Regenerated on every install; edits survive until then. The schema".into());
    line("# is documented in the backend's config/hearth.env.example.".into());
    line(format!("# record completed_unix: {}", completed));
    line(String::new());
    line("# Where things are".into());
    line(format!("HEARTH_BACKEND_DIR={}", slash(&root.join(d::REL_BACKEND))));
    line(format!("HEARTH_PYTHON={}", slash(&root.join(d::REL_PYTHON))));
    line(format!("HEARTH_SUPERVISOR_BIN={}", slash(&root.join(d::REL_SUPERVISOR))));
    line(format!("HEARTH_LLAMA_SERVER_BIN={}", slash(&root.join(d::REL_LLAMA_SERVER))));
    line(format!("HEARTH_HOME={}", slash(&root.join(d::REL_HOME))));
    line(format!("HEARTH_ENGRAM={}", slash(&root.join(d::REL_ENGRAM))));
    line(format!("HEARTH_MODELS={}", slash(&weights_dir)));
    line(format!("HEARTH_LOG_DIR={}", slash(&root.join(d::REL_LOGS))));
    line(String::new());
    line("# The plan's decisions".into());
    if n_ctx > 0 {
        line(format!("HEARTH_LLAMA_CTX={}", n_ctx));
    }
    line(format!("HEARTH_ACCEL={}", accel));
    if let Some(arch) = cuda_arch {
        line(format!("HEARTH_CUDA_ARCH={}", arch));
    }
    line(format!("HEARTH_COEXIST={}", if coexist { 1 } else { 0 }));
    line(String::new());
    line("# Ports: Hearth's own block".into());
    line(format!("HEARTH_PORT={}", d::PORT_GATEWAY));
    line("HEARTH_HOST=127.0.0.1".into());
    line(format!("HEARTH_LLAMA_PORT={}", d::PORT_LLAMA));
    line("HEARTH_LLAMA_HOST=127.0.0.1".into());
    line(format!("HEARTH_RUST_WS_PORT={}", d::PORT_SUPERVISOR_WS));
    line("HEARTH_RUST_WS_HOST=127.0.0.1".into());
    line(format!("HEARTH_RUST_ASSET_PORT={}", d::PORT_SUPERVISOR_ASSETS));
    line("HEARTH_RUST_ASSET_HOST=127.0.0.1".into());
    line(format!("HEARTH_TTS_PORT={}", d::PORT_TTS));
    line(format!("HEARTH_BRAIN_BASE_URL=http://127.0.0.1:{}/v1", d::PORT_LLAMA));
    line(format!("HEARTH_LLAMA_BASE_URL=http://127.0.0.1:{}/v1", d::PORT_LLAMA));
    line(format!("HEARTH_BRAIN_SWITCH_WS_URL=ws://127.0.0.1:{}", d::PORT_SUPERVISOR_WS));
    line(String::new());
    line("# Behaviour".into());
    line("HEARTH_BRAIN_BACKEND=router".into());
    line(format!("HEARTH_TTS_SERVICE_URL=ws://127.0.0.1:{}/tts", d::PORT_TTS));
    line("HEARTH_TTS_BACKEND=remote".into());
    line("HEARTH_TTS_SERVICE=omnivoice".into());
    line("HEARTH_WHISPER_MODEL=base".into());
    line("HEARTH_TOOLS_ENABLED=1".into());
    line("HEARTH_LLAMA_REASONING=auto".into());
    line(format!("HEARTH_DEFAULT_PERSONA={}", d::FIRST_PERSONA));
    line("HEARTH_SESSION_IDLE_S=300".into());

    let config_path = root.join(d::REL_CONFIG);
    if let Some(parent) = config_path.parent() {
        std::fs::create_dir_all(parent).map_err(|e| e.to_string())?;
    }
    std::fs::write(&config_path, out).map_err(|e| e.to_string())?;
    Ok(config_path)
}

/// Re-render on demand, for a repaired or upgraded install.
#[tauri::command]
pub fn probe_render_config(root: String) -> Result<String, String> {
    render(Path::new(&root)).map(|p| p.to_string_lossy().to_string())
}

#[cfg(test)]
mod tests {
    use super::*;

    /// Dev utility, not a test of anything: renders a real install root's
    /// hearth.env through the real code path, so the development machine's
    /// config is generated rather than hand-written. Gated on an env var so
    /// a normal test run never touches disk outside the repo.
    /// Usage: HEARTH_DEV_RENDER_ROOT=D:\Hearth cargo test -p app render_dev_root -- --nocapture
    #[test]
    fn render_dev_root() {
        let Ok(root) = std::env::var("HEARTH_DEV_RENDER_ROOT") else {
            return;
        };
        match render(Path::new(&root)) {
            Ok(path) => println!("rendered {}", path.display()),
            Err(e) => panic!("render failed: {}", e),
        }
    }
}
